- Godeps/Godeps.json
- Godeps/Readme
- Gopkg.lock
- Gopkg.toml
- anagrammer/anagrammer.go
- anagrammer/blank_challenges.go
- anagrammer/build_challenges.go
- anagrammer/rpc_api.go
- docker-compose.yml
- main.go
- vendor/github.com/gorilla/rpc/v2/README.md
- vendor/github.com/gorilla/rpc/v2/server.go
> Revert accidental merge into master

- cmd/bot/main.go
- config/config.go
- runner/parser.go
- runner/printer.go
- runner/runner.go
- runner/settings.go
- shell/api.go
- shell/helptext/challengerule.txt
- shell/helptext/set.txt
- shell/helptext/setlex.txt
- shell/helptext/usage-standard.txt
- shell/shell.go
- Move stuff into runner/ so it can be shared with the bot
- Do not store game options in the game runner
- Only allow lexicon to be set when a game is not active
> Clean up handling of settings

- bot/bot.go
- bot/client.go
- bot/shell.go
Also add pass, exchange and aiplay commands to the bot shell.
> Have the bot pass when opponent plays out.

- _tmp/README
- automatic/game_runner_test.go
- endgame/alphabeta/alphabeta_test.go
- gaddag/dawg.go
- gaddag/utils_test.go
- game/backup.go
- go.mod
- go.sum
- movegen/movegen_test.go
- strategy/exhaustive_leave_test.go
Fix all tests broken by the refactoring
> Refactor game

- docs/manual/autoplay.md
- docs/manual/make_leaves_structure.md
- shell/helptext/autoplay.txt
- strategy/loaders.go
reduce memory usage and startup time
> decompress leaves

- board/board.go
may reduce memory usage.
also preallocate instead of appending.
https://github.com/domino14/liwords/issues/220
> use value type

- endgame/alphabeta/alphabeta.go
- endgame/alphabeta/gamenode.go
- game/game.go
> fix endgame

- board/board.go
things in #123 and an unrelated minor optimization
> improve play legality check

- game/game.go
this fixes https://github.com/domino14/liwords/issues/445 (but not issue 568)
> fix rechallenge on restart

- game/challenge.go
- game/game.go
- game/game_test.go
- game/testdata/history1.json
> Better backups

- automatic/automatic_utils.go
- automatic/game_runner.go
- docs/manual/autoplay.md
- shell/shell.go
`autoplay -lexicon NSF20 -letterDistribution norwegian`
> autoplay -letterDistribution

- cmd/make_leaves_structure/main.go
> sort when building leaves

- gaddag/gaddag.go
https://woogles.io/game/U8hGxrMW?turn=6
> fix gaddag traversal

- anagrammer/anagrammer.go
- board/board.go
- board/board_utils.go
may not be comprehensive.
len(s) counts number of bytes, this affects games in foreign languages.
this patch is untested, but none affects liwords.
> some utf8 support

- montecarlo/montecarlo.go
- montecarlo/stats.go
Fix #43 better - wins are based upon spread at the end of a variation, not based upon change in spread.
> Sim win count improvement

- .gitignore
- game/game.go
- game/id.go
- go.mod
- go.sum
autoplay devotes a very significant chunk of time to generating UUIDs for games! replace id generation function with something much faster.
> speed up id generation

- alphabet/bag.go
- alphabet/bag_test.go
- montecarlo/montecarlo.go
> use fixed order bag for montecarlo sims

- shell/shell.go
> Right-align move table score and equity

- bot/bot.go
- go.mod
- go.sum
> reply if reply channel is given

- endgame/negamax/negamax.go
- endgame/negamax/tiny_move.go
- endgame/negamax/tiny_move_test.go
- endgame/negamax/transposition_table.go
this results in a very modest speed boost.
> re-add hash move optimization. this can result in a speed boost

- endgame/negamax/negamax.go
- endgame/negamax/negamax_test.go
- endgame/negamax/transposition_table.go
- endgame/negamax/transposition_table_test.go
- move/move.go
- scripts/endgame.lua
- shell/api.go
previous lazysmp was a bit faulty.
this works ok with around 6 threads.
> Lazysmp experiments

- game/game.go
- preendgame/peg.go
- preendgame/peg_test.go
- shell/api.go
- shell/helptext/peg.txt
> pre-endgame improvements

- endgame/negamax/solver.go
- endgame/negamax/tiny_move.go
- move/move.go
> don't ever swallow single-move PV

- docs/index.md
- endgame/negamax/solver.go
- preendgame/peg.go
- rangefinder/inference.go
- shell/api.go
- shell/helptext/endgame.txt
- shell/helptext/peg.txt
- shell/script.go
- shell/shell.go
- shell/sim.go
> Shell peg endgame stop

- kwg/kwg.go
sharing wolges's improvement here. untested.
> improve get word index

- endgame/negamax/solver_test.go
- preendgame/peg.go
- preendgame/peg_test.go
> fix cutoff bug for pre-endgame passes

- endgame/negamax/solver.go
> use proper index for shuffle

- .gitignore
- config/config.go
- shell/shell.go
- turnplayer/settings.go
> use the os centralized config dir

- shell/sim.go
fix #390: opprack montecarlo option (alias: fix #384)
> actually pass in known opp rack to sim
